In [3]:
%%time
# Imports
import numpy as np
import pandas as pd

print('Finished imports')



Finished imports
Wall time: 494 ms


In [4]:
%pwd

'c:\\Users\\fe1sw\\Documents\\GitHub\\python-tests\\Learning Data Science'

Boolean Indexing

In [5]:
arr = np.arange(3)

In [7]:
arr[np.array([True, False, True])]

array([0, 2])

In [8]:
arr >= 1

array([False,  True,  True])

In [10]:
arr = np.arange(10)

In [11]:
arr[(arr>2)&(arr<7)]

array([3, 4, 5, 6])

In [15]:
test = bool(1)

test2 = bool(0)

test3 = bool("0")
